server:
  port: 8081

application:
  api_url: http://193.160.208.142:3001

spring:
  rabbitmq:
    host: 'rabbitmq'
    port: 5672
    username: admin
    password: admin
  datasource:
    url: jdbc:postgresql://postgres:5432/orders
    username: 'denis'
    password: 'password'

    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    #      ddl-auto: create-drop
    show-sql: false

queue:
  name: cat_queue